DROP TABLE book;
DROP TABLE author;
DROP TABLE genre;
DROP TABLE dictionary_publisher;

CREATE SEQUENCE seq_author_id START WITH 1 INCREMENT BY 1;

CREATE TABLE author (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_author_id PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  middle_name VARCHAR(255) NOT NULL
);

CREATE SEQUENCE seq_genre_id START WITH 1 INCREMENT BY 1;

CREATE TABLE genre (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_genre_id PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE SEQUENCE seq_dictionary_publisher_id START WITH 1 INCREMENT BY 1;

CREATE TABLE dictionary_publisher (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_dictionary_publisher_id PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE SEQUENCE seq_book_id START WITH 1 INCREMENT BY 1;

CREATE TABLE book (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE seq_book_id PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  genre_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  publisher_id BIGINT NOT NULL,
  city VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  FOREIGN KEY (genre_id) REFERENCES genre(id),
  FOREIGN KEY (author_id) REFERENCES author(id),
  FOREIGN KEY (publisher_id) REFERENCES dictionary_publisher(id)
);

INSERT INTO dictionary_publisher(name) VALUES('Москва');
INSERT INTO dictionary_publisher(name) VALUES('Питер');
INSERT INTO dictionary_publisher(name) VALUES('O’Reilly');